# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51ac0e550992f65ebc9e0ddb2be99ea87eb4cb20724b2021be6643a1c43e9a6f28cdf779f040912acbe0d10195850041ee16fe380ebe330ba2fd54df6acd49f3

test:
  secret_key_base: 1e5c4b5aa41cab057e94e246542cdcc1b999e0cc8bba0ffe0158dbf2cba0cc3c84398d3a2088b8deaf1d4427e421244ce85bf448fa29f9d0744e625c8cfb25c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
